name: flutter_pokemon_clean_architecture
description: A Flutter Pokemon App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  sqflite: ^2.2.8+4
  palette_generator: ^0.3.3+2
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  sqflite_common_ffi: ^2.2.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  dynamic_color: ^1.6.6
  go_router: ^9.0.3
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21
