name: flutter_pokemon_clean_architecture
description: A Flutter Pokemon App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  http: ^1.4.0
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.19.0
  mockito: ^5.4.6
  palette_generator: ^0.3.3+7
  path: ^1.9.1
  rxdart: ^0.28.0
  sqflite_common_ffi: ^2.3.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21
