name: flutter_pokemon_clean_architecture
description: A Flutter Pokemon App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  go_router: ^15.2.4
  http: ^1.4.0
  infinite_scroll_pagination: ^5.1.0
  intl: ^0.20.2
  material_color_utilities: ^0.11.1
  mockito: ^5.4.6
  path: ^1.9.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  sqflite_common_ffi: ^2.3.6
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21
